In [1]:
import numpy as np

### Exercise 1

check the truthness of the following variables/values: 
(try to guess first)

- ""
- 0 -> zero
- []
- [0]

### Answer

In [2]:
bool("")

False

In [3]:
bool(0)

False

In [4]:
bool([])

False

In [5]:
bool([0])

True

---

### Exercise 2

You are given three numerical variables, a, b and c. Write a code that:
- prints "a is the biggest" if a is bigger than both b and c
- prints "a is bigger than one of them" if a is bigger than b or c
- prints "a is the smallest" if a is smaller than both b and c

In [6]:
a = 10
b = 9
c = 18

### Answer

In [7]:
if (a > b) and (a > c):
    print("a is the biggest")
elif (a > b) or (a > c):
    print("a is bigger than b or c")
else:
    print("a is the smallest")

a is bigger than b or c


---

### Exercise 3

Implement the following diagram.

![exercise3](flow_chart_ex3.png)

In [8]:
score = 85

### Answer

In [9]:
if score > 75:
    print("You passed the first level")
    if score > 90:
        print("You are directly accpeted")
    else:
        print("You will have an interview soon")
else:
    print("Unfortunately you did not pass!")

You passed the first level
You will have an interview soon


---

### Exercise 4

In previous exercise (Exercise 3), we have if statement inside another if statement (two levels of conditions). Try to write a code with same functionality with one level of conditions.

### Answer

In [10]:
if score > 90:
    print("You passed the first level")
    print("You are directly accepted")
elif (score > 75) and (score <= 90):
    print("You passed the first level")
    print("You will have an interview soon")
else:
    print("Unfortunately you did not pass!")

You passed the first level
You will have an interview soon


---

### Exercise 5

You are provided with an array. Find the location of a given value in this array.

In [11]:
my_array = np.random.randint(0, 21, (30,))
my_array

array([14,  9, 18, 12,  7,  4, 19, 12, 14, 14, 15,  7,  5, 15, 13, 16, 15,
       20, 11, 17, 17, 19, 18, 12,  9,  3, 14,  3,  3,  3])

In [12]:
value = 10

### Answer

In [13]:
loc = np.where(my_array == value)
loc[0]

array([], dtype=int64)

---

### Exercice 6

You are provided with two sets of datapoints. you are required to:
- Find the period of intersection.

In [14]:
data_1 = np.array(([0] * 5 + [1] * 5 + [0] * 5))
data_2 = np.array(([0] * 3 + [1] * 5 + [0] * 7))
timing = np.linspace(0, 140, data_1.size)

In [15]:
data_1

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [16]:
data_2

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [17]:
timing

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
       110., 120., 130., 140.])

### Answer

In [18]:
timing_intersect = timing[(data_1==1) & (data_2==1)]
timing_intersect[-1] - timing_intersect[0]

20.0

---

### Exercise 7

You are given an array, called "`result`", with 100000 values. find how many times each unique element is repeated in this array.<br>
**Hint**: To find unique values in a numpy array, look into np.unique() method.

In [19]:
result = np.random.randint(1,7,(100000,))

### Answer

In [20]:
np.unique(result)

array([1, 2, 3, 4, 5, 6])

In [21]:
frequency = []
for val in np.unique(result):
    freq = np.sum(result == val)
    frequency.append(freq)

In [22]:
frequency

[16790, 16605, 16610, 16667, 16716, 16612]

### Answer (alternative)

As usual, there are already existing functions we can use to do a specific task:

In [23]:
uniqs, counts = np.unique(result, return_counts=True)

In [24]:
uniqs

array([1, 2, 3, 4, 5, 6])

In [25]:
counts

array([16790, 16605, 16610, 16667, 16716, 16612], dtype=int64)

### Exercise 8

Following the previous exercise, change all the odd numbers to 0 and all the even number to 1 in the given array "`result`", and check the frequency again

### Answer

In [26]:
result[result % 2 == 0] = 0
result[result != 0] = 1

In [27]:
result

array([0, 0, 1, ..., 0, 0, 1])

In [28]:
frequency = []
for val in np.unique(result):
    freq = np.sum(result == val)
    frequency.append(freq)

In [29]:
frequency

[49884, 50116]

---