# Exercise 2.3

1) Import the numpy package under the name `np`.

In [2]:
import numpy as np

## Creating numpy arrays

Numpy provides several ways to create numpy arrays. Use `np.zeros()`, `np.ones()`, `np.arange()`, `np.random.randn()`, `np.linspace()` to create numpy arrays in the following tasks.

2) Create a vector with values ranging from 0 to 10.

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3) Create a vector ranging from 5 to 10.

In [5]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

4) Create a vector of zeros with 10 elements

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

5) Create a vector of ones with 10 elements

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

6) Create a vector ranging from 0 to 10, where the difference between each value is .1, instead of 1.

In [8]:
np.arange(0, 10, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

7) Create a vector starting from 10.2, ending on 12, with 20 elements.

In [12]:
np.linspace(10.2, 12, 10)

array([10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ])

8) Create a 3x3 numpy array with random values.

## Data Inspection

Before starting to work with any data, it's a good idea to get some insight about the data:
- How many dimensions does it have
- How many elements does it have in each dimensions (mainly number of rows, columns)

9) How many dimension does the following numpy array have?

In [14]:
my_arr = np.array([[1., 2., 3.], [4., 5., 6.]])

10) How many elements does it have in each dimension (i.e., what is the shape of it)?

11) What is the data type of the elements of `my_arr`?

12) Create a 3x3 numpy array ranging from 0 to 9. Name this array `my_arr`.

In [ ]:
my_arr = np.array()

<br>
Sometimes, we might need to create an array based on the dimensions of another.

13) Create a numpy array of zeros same size as `my_arr`.

14) Resize `my_arr` to become a vector (only with one dimension).

## Aggregation and transformation

I have sent you a file (in Slack) which includes a numpy array.

15) Download and load the file in the notebook

16) Find the following information about the array
- minimum value
- maximum value
- mean
- std
- row and column with minimum values
- row and column with maximum values
- mean of each column (though rows)
- mean of each row
- std of each row
- std of each column

For the following two numpy arrays, perform the following element-wise operations using numpy functions.

In [19]:
a_arr = np.arange(10, 51, 5)
b_arr = np.arange(1, 11)

17) Divide `a_arr` by `b_arr`.

18) What is the remainder of previous operation?

19) multiply the 3rd column of th following array by 2

In [22]:
my_arr = np.random.randint(0, 10, size=(3, 3))
my_arr

array([[9, 1, 8],
       [9, 2, 0],
       [0, 2, 2]])

20) Raise the last row of the following array to the power of 5.

In [23]:
my_arr = np.random.randint(0, 10, size=(5, 5))

21) Let's try an explore a new function: `np.pad()`. <br>

a) Go through the documentation (docstring) of `np.pad()` function and try to understand how does it work.

b) Create the following matrices using the functins we learnt already and Numpy's `pad()` function

<div style="text-align:center">
    <img src ="https://github.com/mohammadbashiri/MPI-python-workshop-2019/blob/master/img/padding_ex_1.png?raw=true" height="300" width="300" style="border:0px;margin:50px"/>
    <img src ="https://github.com/mohammadbashiri/MPI-python-workshop-2019/blob/master/img/padding_ex_2.png?raw=true" height="200" width="200" style="border:0px;margin:90px"/>
</div>