- [ ] [C] Numpy (cont.)
    - Masking
    - Combining and Splitting
    - Vectorization

1) Create 4x4 numpy array ranging from 0 to 16. Name is `my_arr`

In [14]:
import numpy as np

In [15]:
my_arr = np.arange(16).reshape(4, 4)

In [16]:
my_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

2) Extract the diagonal of this array. <br>
**Hint**: use `np.eye()` and masking

In [22]:
my_arr[np.eye(*my_arr.shape) == 1]

array([ 0,  5, 10, 15])

3) Make all the elements in `my_arr`, except the diagonal, zero.

In [23]:
my_arr[np.eye(*my_arr.shape) == 0] = 0

In [24]:
my_arr

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

4) Using a numpy function, find the index of the non-zero values in the given list. <br>
**Hint**: Look into `np.nonzero()`

In [36]:
my_list = [1, 0, 0, 10, 0, -3]

In [37]:
np.nonzero(my_list)

(array([0, 3, 5]),)

5) Change `my list` to a numpy array and find the non-zero element of the resulting array.

In [38]:
my_arr = np.array(my_list)

In [39]:
my_arr[my_arr != 0]

array([ 1, 10, -3])

6) Using the numpy function `np.where()` find the index of the non-zero element of the array from previous exercise.

In [42]:
np.where(my_arr != 0)

(array([0, 3, 5]),)

7) Given a 1D array, negate all elements which are between 3 and 8, in place.

In [43]:
x = np.arange(11)

8) Create a random 1D numpy array of size 10 and with integer values. Name it `int_arr`.

In [44]:
int_arr = np.random.randint(0, 10, size=(10))

In [45]:
int_arr

array([4, 2, 8, 4, 0, 8, 4, 3, 7, 9])

9) Sort this array in descending order. <br>
**Hint**: Look into `np.sort()`

10) Two arrays are given below, `a_arr` and `b_arr`. 
- Sort `a_arr` in descending
- Sort `b_arr` with the same order of elements as `a_arr`

**Hint**: Look into `np.argsort()`

11) Sort the following array by the 1st, 3rd, and last column?

In [54]:
my_arr = np.random.randint(0, 20, size=(7, 10))
my_arr

array([[ 2, 14, 16,  4, 11,  6, 14, 19,  6, 12],
       [15, 18,  9,  2,  7,  8, 19, 15, 17,  4],
       [ 1, 18,  5,  1,  4,  7,  0,  5, 12, 11],
       [ 4, 15,  5, 18, 17,  1,  7,  1,  0,  1],
       [12, 19, 11, 15, 18, 16,  0, 11,  7,  0],
       [ 9,  9, 15, 17, 12, 12,  6,  1, 15,  4],
       [11, 17, 13,  0, 10,  8,  1, 11,  1, 15]])

In [57]:
my_arr[np.argsort(my_arr[:, 0]), :]

array([[ 1, 18,  5,  1,  4,  7,  0,  5, 12, 11],
       [ 2, 14, 16,  4, 11,  6, 14, 19,  6, 12],
       [ 4, 15,  5, 18, 17,  1,  7,  1,  0,  1],
       [ 9,  9, 15, 17, 12, 12,  6,  1, 15,  4],
       [11, 17, 13,  0, 10,  8,  1, 11,  1, 15],
       [12, 19, 11, 15, 18, 16,  0, 11,  7,  0],
       [15, 18,  9,  2,  7,  8, 19, 15, 17,  4]])

In [58]:
my_arr[np.argsort(my_arr[:, 2]), :]

array([[ 1, 18,  5,  1,  4,  7,  0,  5, 12, 11],
       [ 4, 15,  5, 18, 17,  1,  7,  1,  0,  1],
       [15, 18,  9,  2,  7,  8, 19, 15, 17,  4],
       [12, 19, 11, 15, 18, 16,  0, 11,  7,  0],
       [11, 17, 13,  0, 10,  8,  1, 11,  1, 15],
       [ 9,  9, 15, 17, 12, 12,  6,  1, 15,  4],
       [ 2, 14, 16,  4, 11,  6, 14, 19,  6, 12]])

In [59]:
my_arr[np.argsort(my_arr[:, -1]), :]

array([[12, 19, 11, 15, 18, 16,  0, 11,  7,  0],
       [ 4, 15,  5, 18, 17,  1,  7,  1,  0,  1],
       [15, 18,  9,  2,  7,  8, 19, 15, 17,  4],
       [ 9,  9, 15, 17, 12, 12,  6,  1, 15,  4],
       [ 1, 18,  5,  1,  4,  7,  0,  5, 12, 11],
       [ 2, 14, 16,  4, 11,  6, 14, 19,  6, 12],
       [11, 17, 13,  0, 10,  8,  1, 11,  1, 15]])

12) For the given array:
- subtract the mean of each column from the column
- divide each column by the standard deviation of the column

In [62]:
my_arr = np.random.randn(20, 3)
my_arr

array([[-0.42265228, -1.05683839, -1.52379009],
       [ 1.42317119,  0.62008853, -0.44762063],
       [ 2.04230403, -0.63899089, -1.80156999],
       [-1.4219904 , -1.24063795, -0.12025273],
       [-0.3313051 , -2.39351079,  0.08152036],
       [-0.77257543,  1.56111785, -0.06391544],
       [-0.18270055, -0.10021046, -0.93830607],
       [-0.45790338, -1.0726902 ,  0.69006883],
       [ 0.6104872 ,  0.88829542,  0.91071152],
       [ 0.95378398,  0.97317826, -1.65970527],
       [ 0.3484132 , -0.87474744, -0.10382639],
       [-1.09594464, -1.23660486, -0.59471798],
       [-1.70525379,  1.19542776,  0.0585976 ],
       [ 0.21684956,  0.81006431, -1.29136043],
       [ 1.95234957, -0.41771678,  0.27430331],
       [ 0.37269018, -0.30099155, -1.81428155],
       [-0.29725074, -0.41889692, -1.05517569],
       [-0.33510575,  2.22009308, -0.05420652],
       [-0.13628138,  1.01709479, -1.20087444],
       [-1.28293284, -0.22017513,  1.45969825]])

12) Using a the numpy function `mean()` and `std`, define a function that get a numpy array and returns a standardized version of it. This standardization must be perform for each column separately.

13) Create a random array of size 50x4. And
- Using the function created in previous exercise, standardize each column
- Plot the first column of the original array and the standardized version, using a line plot

14) Perform the following task on the two given arrays
- change the type of the array elements to `np.float`. **Hint**: `astype()`
- stack the two arrays vetically
- save the resulting stacked array
- share your file via slack with me