In [1]:
import numpy as np

# Boolean Operations and Indexing

In this tutorial you will learn to:
- use if-statements to control program flow
- write Boolean logic expressions
- combine multiple logic expressions using:
    - and
    - or
    - not
- extract sub-array(s) from your data array
- manipulate sub-array(s) in a array

---

## What is a boolean?

Boolean values are the two constant objects **False** and **True**. 

They are used to represent truth values (although other values can also be considered false or true). In numeric contexts (for example when used as the argument to an arithmetic operator), they behave like the integers 0 and 1, respectively.

In [2]:
print(True)

True


Note the **uppercase**!

In [3]:
print(true)

NameError: name 'true' is not defined

In [4]:
print(False)

False


In [5]:
print(type(True))

<class 'bool'>


In [6]:
int(True)

1

In [7]:
int(False)

0

In [8]:
str(True)

'True'

The built-in function bool() can be used to convert any value to a Boolean, if the value can be interpreted as a truth value - that basically means if we wanna check the truthness of something, we can just use `bool(something)`.

In [9]:
bool(0)

False

In [10]:
bool(1)

True

In [11]:
bool('')

False

In [12]:
bool('abc')

True

Note: the following values are interpreted as false: False, None, numeric zero of all types, and empty strings and containers (including strings, tuples, lists, dictionaries, sets and frozensets). All other values are interpreted as true.

## Inequality operations

We can perform all kinds of inequality operations in python. Here is a table:

![Conditional Expressions](ConditionalExpressions.png)

In [13]:
a = 5

In [14]:
a > 3

True

In [15]:
a < 10

True

In [16]:
a > 10

False

In [17]:
a >= 5

True

In [18]:
a == 5 

True

In [19]:
a != 4

True

And as we can see the output of these inquality operation are booleans. Let's check that:

In [20]:
type(a > 4)

bool

We can also do:

In [21]:
5 < a < 10

False

In [22]:
5 <= a < 10

True

In [23]:
4 == a < 10

False

What is happening is that ppython would take these two conditions and under the hood separates them and applies AND to them

---

## Control Program Flow

We learned about if statement as a tool to control the flow of the operations performed in our code. if statements run if their arguments is ***true***, which is a boolean. So we can control the flow by performing operations that output boolean states.

```python
if condition_1:

    do something

else:

    do something
```

![title](https://www.programiz.com/sites/tutorial2program/files/Python_if_else_statement.jpg)

In [24]:
a = 5

In [25]:
if a > 2:
    print('Argument of "if" evaluated to True')

Argument of "if" evaluated to True


In [26]:
if a < 2:
    print('Argument of "if" evaluated to True')
else:
    print('Argument of "else" evaluated to True')

Argument of "else" evaluated to True


In [27]:
a = 5
b = 3

Remember

In [28]:
a == b

False

In [29]:
if a == b:
    print('two values are equal')
else:
    print('Not equal!')

Not equal!


In [30]:
if a > b:
    print('a is greater than b')
else:
    print('a is either equal to b, or smaller than b')

a is greater than b


Multiple conditions..

```python
if condition_1:

    do something

elif condition_2:
    do something
    
else:

    do something
```

![pic](https://www.tutorialgateway.org/wp-content/uploads/ELSE-IF-Flow-Chart.jpg)

In [31]:
a = b

if a > b:
    print("a is bigger than b")
elif a < b:
    print("a is smaller than b")
else:
    print("a is equal to b")

a is equal to b


And we can have as many conditions as we want.

#### Some Important Points

* Note that by using if, elif, and else we are imposing a priority on conditions:

In [32]:
a = 5
b = 3

if a > b:
    print("a is bigger than b")
elif a > 3:
    print("a is bigger than 3")
else:
    print("a is smaller than both 3 and b")

a is bigger than b


Note that both of the following conditions are True:
- a > b
- a > 3

But, since if has priority upon elif (or any subsequent condition), it runs the code under if.

* Also note that we can get rid of this priority by using multiple if statements

In [33]:
a = 5
b = 3

if a > b:
    print("a is bigger than b")
if a > 3:
    print("a is bigger than 3")
else:
    print("a is smaller than both 3 and b")

a is bigger than b
a is bigger than 3


When we use an if, then the following elif and else statements are attached to it, and prioritized accordingly.

---

What if we want to check multiple conditions?

## Boolean operations (AND, OR, and NOT)

**Note**: I am using capitalized "and", "or", and "not" keywords to make a distinction between a command and a simple word. in python these are all lowercase.

While using the boolean AND, OR, a NOT operations, the following values are interpreted as false: False, None, numeric zero of all types, and empty strings and containers (including strings, tuples, lists, dictionaries, sets and frozensets). All other values are interpreted as true.

The operator NOT yields True if its argument is False, False otherwise.

The expression x AND y first evaluates x; if x is False, its value is returned; otherwise, y is evaluated and the resulting value is returned.

The expression x OR y first evaluates x; if x is True, its value is returned; otherwise, y is evaluated and the resulting value is returned.

```python
something_true and x -> x
something_false and x -> something_false
something_true or x -> something_true
something_false or x -> x
```

We are gonna focus on AND and OR in this tutorial, but feel free to explore the OR operations.

In [34]:
s = ""
s or 'foo'

'foo'

In [35]:
s and 'foo'

''

In [36]:
1 and 'everything' or 'nothing'

'everything'

In [37]:
0 and 'everything' or 'nothing'

'nothing'

Note that **and** has priority upon **or**.

In [38]:
4 > 2 and 3 < 5

True

Now we have way to combine multiple conditions and use the combination as if statement condition:

In [39]:
if (4 > 2) and (3 < 5):
    print('It evaluated the condition as True')
else: 
    print('It evaluated the if condition as False')

It evaluated the condition as True


---

There is another application that booleans can be really helpful with. 

## Extracting Information From Data (Indexing)

Booleans can be used to index arrays.

In [40]:
a = np.random.randint(0, 10, (10,))
a

array([3, 3, 1, 5, 4, 7, 2, 1, 6, 1])

Now we can gain some insight about our data, using boolean indexing. For example, is the any value equal to 10 in my data:

In [41]:
a == 5

array([False, False, False,  True, False, False, False, False, False,
       False])

How many of them?

In [42]:
a[a==5]

array([5])

We can perform other operations:

In [43]:
a % 2 == 0  # even values

array([False, False, False, False,  True, False,  True, False,  True,
       False])

In [44]:
a[a % 2 == 0]

array([4, 2, 6])

In [45]:
a <= 4

array([ True,  True,  True, False,  True, False,  True,  True, False,
        True])

In [46]:
a[a <= 4]

array([3, 3, 1, 4, 2, 1, 1])

We can also use one array to index another array

In [47]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b = np.arange(6,15)
b

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

Normal indexing

In [49]:
b[1:3]

array([7, 8])

What if I want the elements that are bigger than, let's say, 3?

In [50]:
a > 3

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [51]:
b[a > 3]

array([ 9, 10, 11, 12, 13, 14])

What if we want a combination of conditions?

In [52]:
b[(a > 3) and (a < 7)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Boolean operation wouldn't be helpful for arrays, because the condition is evaluated on each element, and python doesn't know which element should it consider to continue.

In order to get booleans based on comaprisons on the elements of an array we need to perform **bitwise logical operations**.

What does "**bitwise**" mean?

In [53]:
example_1 = np.array([1, 0, 1, 0])
example_2 = np.array([0, 0, 1, 0])

The following code will give us an error, as before:

In [54]:
example_1 and example_2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [55]:
example_1 & example_2

array([0, 0, 1, 0], dtype=int32)

- "&" is the bitwise AND operation
- "|" is the bitwise OR operation

In [56]:
example_1 | example_2

array([1, 0, 1, 0], dtype=int32)

So.. to get a piece of our array:

In [57]:
b

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
b[(a > 3) & (a < 7)]

array([ 9, 10, 11])

In [59]:
b[(a < 3) | (a > 7 )]

array([ 6,  7, 13, 14])

---

## Sub-array Data Manipulation

In [60]:
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
a[(a > 14) & (a < 25)] = 0
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

---

## References

1. [Python official documentation on if statement](http://anh.cs.luc.edu/python/hands-on/3.1/handsonHtml/ifstatements.html)
2. [Python official documentation on expressions](https://docs.python.org/3.5/reference/expressions.html#boolean-operations)
3. [Short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation)